import { render } from '@testing-library/react';
import { describe, expect, it } from 'vitest';

import RootLayout, { metadata } from './layout';

describe('Metadata', () => {
  it('should have correct metadata', () => {
    expect(metadata.title).toBe('Create Next App');
    expect(metadata.description).toBe('Generated by create next app');
  });
});

const mockChildren = <div data-testid="child-element">Hello World</div>;

describe('RootLayout Component', () => {
  it('should render its children correctly', () => {
    const { getByTestId } = render(<RootLayout>{mockChildren}</RootLayout>);
    expect(getByTestId('child-element')).toBeInTheDocument();
  });

  it('should apply the correct attributes to html and body elements', () => {
    const { container } = render(<RootLayout>{mockChildren}</RootLayout>);
    const html = container.innerHTML;

    expect(html).toContain('class="');
    expect(html).toContain('mock-font-variable');
    expect(html).toContain('antialiased');

    expect(html).toContain('lang="en"');
  });
});
